#!/usr/bin/env python3
from shutil import which
from pathlib import Path
import subprocess
from argparse import ArgumentParser
import csv
import os
import re
from urllib.request import urlopen
from datetime import date, timedelta
import calendar
import datetime

# favor não executar esse script diretamente para evitar dar carga para o serviço deles

THIS_FOLDER = Path(__file__).parent
os.chdir(THIS_FOLDER)

JOINED_CSV = THIS_FOLDER / "joined.csv"

data = urlopen("https://www.portaldefinancas.com/js-tx/cdidiaria.js").read().decode('utf-8')

ITEM_REGEX = re.compile(r"<td>(?P<day>[0-9]{2})/(?P<month>[0-9]{2})/(?P<year>[0-9]{2})</td><td>(?P<rate>[0-9,]*)</td>")

columns = ["day", "value.day"]

if not JOINED_CSV.exists():
    with JOINED_CSV.open('w') as f:
        w = csv.DictWriter(f, columns)
        w.writeheader()

structured_data = {}
with JOINED_CSV.open('r') as f:
    for item in csv.DictReader(f, columns):
        if item['day'] == 'day':
            continue
        parsed_date = datetime.datetime.strptime(item['day'], '%d-%m-%Y').date()
        structured_data[parsed_date] = item['value.day']

for match in re.finditer(ITEM_REGEX, data):
    item = match.groupdict()
    parsed_date = datetime.datetime.strptime(f"{item['day']}-{item['month']}-{item['year']}", '%d-%m-%y').date()
    structured_data[parsed_date] = item['rate'].replace('.', '').replace(',', '.')

with JOINED_CSV.open('w') as f:
    w = csv.DictWriter(f, columns)
    w.writeheader()
    days = list(structured_data.keys())
    days.sort()
    for day in days:
        w.writerow({
            'day': day.strftime('%d-%m-%Y'),
            'value.day': structured_data[day]
        })

    
