#!/usr/bin/env python3

from pathlib import Path
import sys
from datetime import date, datetime
import logging
from csv import DictWriter

CURRENT_DIR=Path(__file__).resolve().parent
sys.path.append(str(CURRENT_DIR.parent.parent.parent / "src"))

from core.http import fetch_json
from core.models import Entry

logging.basicConfig()
logger = logging.getLogger(__name__)

TODAY = datetime.today().date()

content = fetch_json("https://www.tesourodireto.com.br/json/br/com/b3/tesourodireto/service/api/treasurybondsinfo.json")
items = [item['TrsrBd'] for item in content['response']['TrsrBdTradgList']]
for item in items:
    output_file = CURRENT_DIR / "tesourodireto" / (item['nm'] + '.csv')
    output_file.parent.mkdir(parents=True, exist_ok=True)
    entry = Entry(day=TODAY, price=item['untrRedVal'])
    if not output_file.exists():
        with output_file.open('w') as f:
            w = DictWriter(f, fieldnames=entry.columns)
            w.writeheader()
    with output_file.open('a') as f:
        w = DictWriter(f, fieldnames=entry.columns)
        w.writerow(entry.line)
