#!/usr/bin/env python3

from pathlib import Path
import csv
from urllib.request import urlopen
import json
from datetime import date
import calendar

CURRENT_DIR=Path(__file__).parent
JOINED_CSV=CURRENT_DIR / "joined.csv"

fetched = json.load(urlopen("https://api.bcb.gov.br/dados/serie/bcdata.sgs.16122/dados?formato=json"))

with JOINED_CSV.open('w') as f:
    w = csv.DictWriter(f, ['day', 'value.month'])
    w.writeheader()
    for item in fetched:
        _, month, year = item['data'].split('/')
        _, day = calendar.monthrange(int(year), int(month))

        valor = item['valor']
        w.writerow({
            'day': date(int(year), int(month), day),
            'value.month': valor
        })
