name: CI/Release

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  MISE_VERBOSE: 1
  MISE_YES: 1
  # Disable mise GitHub integration
  MISE_GITHUB_ACTION: "0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install mise
        run: |
          mkdir -p ~/.local/bin
          curl -L https://mise.jdx.dev/mise-latest-linux-x64 > ~/.local/bin/mise
          chmod +x ~/.local/bin/mise
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ""
          CI: "false" # Prevent mise from detecting CI and reporting status
        run: mise install

      - name: Codegen
        env:
          GITHUB_TOKEN: ""
          CI: "false"
        run: mise run codegen

      - name: Create PR or Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: ./scripts/release.sh

      - name: Lint
        env:
          GITHUB_TOKEN: ""
          CI: "false"
        run: mise run lint

      - name: Test
        env:
          GITHUB_TOKEN: ""
          CI: "false"
        run: mise run test

      - name: Prepare Artifacts
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: zip -r data.zip bruto

      - name: Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG_NAME="release-$(date +%Y%m%d%H%M%S)"
          fi
          gh release create "$TAG_NAME" data.zip --generate-notes

      - name: Upload Artifacts to Workflow
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data.zip
